//
// Created by n on 15/08/2026.
//

#ifndef RAYLIB_STG_MENULIST_H
#define RAYLIB_STG_MENULIST_H
typedef enum
{
    MENU_MAIN = 0,
    MENU_CONTROLS,
    MENU_CONTROLS_GAMEPAD,
    MENU_CONTROL_DEVICE_SELECTION,

    MENU_COUNT
}MENUS;
#endif //RAYLIB_STG_MENULIST_H